[package]
name = "universal-util"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rfd = "0.14"          # Native Windows file dialogs
image = "0.24"        # Pixel manipulation & Nearest-Neighbor
oxipng = "9.1"        # Lossless PNG reduction
rayon = "1.8"         # Multi-core parallel processing
anyhow = "1.0"
infer = "0.19"           # Detects file types by checking headers (magic numbers)
rust_ffmpeg = "0.1"# Professional error handling



[build-dependencies]
slint-build = "1.6" # Compiles your .slint UI files to Rust code
cc = "1.0"          # Allows Rust to compile your C++ files during 'cargo build'
